require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

target 'App' do
  capacitor_pods
  
  # 유니티 Ads SDK (직접 추가하셨던 부분)
  pod 'UnityAds', '4.12.5' 
end